### ISSUE TITLE
eventScroll offset

### ISSUE THREAD

**Issue by giando110188** [nicholasruggeri/cookies-enabler#10]
Secondo me ci vorrebbe un'opzione per definire un offset (in pixel) oltre il quale allo scroll il banner scompare. Così scompare anche se scorri per sbaglio di uno solo pixel.

**Comment by giando110188** [comment]
Se ti interessa io ho già risolto così:

``` javascript
if (opts.eventScroll === true) {

    window.addEventListener('load', function()
    {
        var start_Y = window.pageYOffset;
        window.addEventListener('scroll', function()
        {
            if (Math.abs(window.pageYOffset - start_Y) > opts.scrollOffset) enableCookies();
        });
    });

}
```

ho aggiunto l'opzione "scrollOffset". Poi in questo modo (usando l'evento "load") si risolve anche il problema che se carichi la pagina e lo scroll non è a 0 (ad esempio se vai direttamente su un ancora) viene considerato lo "start_Y" in base a dove ti trovi quando la pagina è caricata.

**Comment by nicholasruggeri** [comment]
Grazie @giando110188! Riesci a fare una pull request?

**Comment by giando110188** [comment]
Non sono espertissimo di GitHub, però ci provo...

**Comment by giando110188** [comment]
Penso di esserci riuscito
