### ISSUE TITLE
Problema con Google Analytics

### ISSUE THREAD

**Issue by stileinverso** [nicholasruggeri/cookies-enabler#11]
Da quando c'è stato l'aggiornamento che ha permesso di disabilitare gli iframe, sia Google Analytics che Facebook hanno smesso di funzionare (non appaiono più nonostante abbia accettato i cookie). Ho notato questo problema anche nella vs demo allegata. È normale oppure c'è da fare altro?

**Comment by ramspeed** [comment]
Stesso errore anche a me :(

**Comment by stileinverso** [comment]
Infatti, ripristinando il vecchio file "cookies-enabler.js", sia GA che FB tornano a funzionare normalmente.

**Comment by ramspeed** [comment]
Sisi stessa cosa

**Comment by nicholasruggeri** [comment]
Eccoci. Piccolo refuso di sviluppo.
Tutto sistemato.
