### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by biapar** [nicholasruggeri/cookies-enabler#17]
Hi, good and simple solution -:)
Is't reload page?
Is't possibile a selective on/off some type of cookies?

**Comment by gsimone** [comment]
Hi,
if you want to reload the page after the cookies are enabled, use the onEnabled callback in the options.

Example:

COOKIES_ENABLER.init({

   onEnabled: function(){ location.reload(); }

});

The feature for cookie types is coming in the near future, we are in the design phase at the moment.

**Comment by biapar** [comment]
Why is not insert this by default?

**Comment by biapar** [comment]
Facendo il reload sull'init causa il reload di ogni pagina nel sito. Andrebbe fatto sull'OK.
