### ISSUE TITLE
iframes.get

### ISSUE THREAD

**Issue by gsndr** [nicholasruggeri/cookies-enabler#21]
When I accept cookies script work and frames is visible, but if I return in the page frames are hide.
The problem is in get function. First  n = iframes.length is 1, second time is 0.
But I can't find the problem

**Comment by gsimone** [comment]
Are you on the latest version? If not, please, try it and let me know if the problem still exists.

**Comment by gsndr** [comment]
No, I tried and I have the same problem.

**Comment by gsndr** [comment]
It's this problem https://github.com/nicholasruggeri/cookies-enabler/issues/7. If I move the script to the footer area of the websit, it works correctly.
