### ISSUE TITLE
enable cookies by click

### ISSUE THREAD

**Issue by uruk-hai-21** [nicholasruggeri/cookies-enabler#22]
Great work!
I noticed that if I click the link of Privacy Policy are enabled the cookies. Is it possible exclude the link of Privacy Policy?

PS
Dimmi di dove sei e hai una birra pagata!

**Comment by gsimone** [comment]
Hey, I fixed this bug on the develop branch this morning. We will release a new production version soon, but you can use that one in the meantime.

EDIT: Now released

**Comment by gsimone** [comment]
Ps. se vuoi offrirci una birra, abbiamo aggiunto un link a paypal nella documentazione :beer:
