### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by ramspeed** [nicholasruggeri/cookies-enabler#24]
Ciao, è possibile disabilitare il click con il tasto destro?

**Comment by gsimone** [comment]
Intendi dire disabilitarlo completamente?

**Comment by ramspeed** [comment]
Si esatto solo il tasto destro
Il 31/mag/2015 22:01, "Gianmarco" notifications@github.com ha scritto:

**Comment by nicholasruggeri** [comment]
@ramspeed, per curiosità, perché vorresti questa feature?

**Comment by ramspeed** [comment]
Perché se clicco con il tasto detto per vedere i cookie... si attivano e
non posso controllare.
Il 01/giu/2015 12:22, "Nicholas Ruggeri" notifications@github.com ha
scritto:

**Comment by nicholasruggeri** [comment]
@ramspeed, mi spiace. Al momento non prevediamo questa funzionalità.
Puoi aprire la console, se sei mac, con cmd+alt+c.
