### ISSUE TITLE
Problema nel confronto document.getElementById('ce-banner-html') !== null 

### ISSUE THREAD

**Issue by biapar** [nicholasruggeri/cookies-enabler#27]
Pur avendo inserito nella home un 

 <script id="ce-banner-html" type="text/plain">
      <p>
        Per offrire una migliore esperienza di navigazione, per avere statistiche relative all'uso dei nostri servizi e per farti visualizzare contenuti pubblicitari in linea con le tue preferenze ed esigenze, questo sito usa cookie anche di terze parti. Chi sceglie di proseguire nella navigazione o di cliccare al di fuori di esso, esprime il consenso all'uso dei cookie.
      </p>
      <p>
        <a href="#" class="ce-accept">Accetto</a> <a href="#" class="ce-disable">Non Accetto</a> or <a href="/cookie-policy/">Informativa</a>
        <a href="#" class="ce-dismiss">X</a>
      </p>
    </script>

il confronto 
document.getElementById('ce-banner-html') !== null ?
ritorna sempre null

**Comment by nicholasruggeri** [comment]
Ciao @biapar, così ad occhio direi che hai messo lo script con il template del banner dopo l'inclusione del file. Prova a metterli prima dell'inclusione.

**Comment by biapar** [comment]
Ops..ho messo il javascript nell'header ed il template dopo il footer.

**Comment by nicholasruggeri** [comment]
Io metterei tutti i js poco prima la chiusura del body ;)
