### ISSUE TITLE
Elenco feature

### ISSUE THREAD

**Issue by andyprog** [nicholasruggeri/cookies-enabler#28]
Salve,
è possibile avere un elenco delle feature che pensate di implementare? 
Consigliate di usare lo script già allo stato attuale?

grazie

**Comment by nicholasruggeri** [comment]
Nei prossimi giorni inseriremo un readme con le prossime feature.
Allo stato attuale (release 1.2+) il codice è stabile e viene usato in molti, da piccoli a grossi.

**Comment by andyprog** [comment]
Grazie.
Il js e la'iniziazione dello script devono andare obbligatoriamente dopo tutti gli altri script che generano cookie?

**Comment by nicholasruggeri** [comment]
La cosa fondamentale è che sia prima della chiusura del body. Ricordati che i template js con dentro l'html devono essere prima dell'inclusione di cookies-enabler.js.
