### ISSUE TITLE
Android 4.2.2 problem

### ISSUE THREAD

**Issue by AndreaBaccolini** [nicholasruggeri/cookies-enabler#29]
Purtroppo ho notato che il tuo script non funziona nel browser di android 4.2.2. Quando ho un'iframe, e clikko sul messaggio per farlo comparire, non scompare ne il banner ne il messaggio.

Stessa cosa succede con IE 10 desktop e su IE9 non compare il pulsante di sblocco degli iframe

Praticamente con il iframesPlaceholder da errore (IE addiritutra mi si è impallato). 

Mi correggo l' iframesPlaceholder da errore anche se disabilitato su IE (impalla il browser) mentre sul browser di android funziona se disabilitato

**Comment by nicholasruggeri** [comment]
@AndreaBaccolini ci stiamo lavorando i questo momento.
