### ISSUE TITLE
adsense in wrong

### ISSUE THREAD

**Issue by gianfire** [nicholasruggeri/cookies-enabler#32]
```
<script type="text/plain" class="ce-script"
 src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
 </script>
```

this dont work

**Comment by nicholasruggeri** [comment]
Hello @gianfire, this problem is the same as #31 .
We're working on.

**Comment by gianfire** [comment]
l'errore non sembra lo stesso questo è riferito agli ads di google. 
comunque siete riusciti a risolvere qualcosa?
