### ISSUE TITLE
IE8 compatibility bug

### ISSUE THREAD

**Issue by lianix1** [nicholasruggeri/cookies-enabler#36]
Buongiorno, ho installato lo script, ma ho notato che non funziona su ie8.
Non riesco a capire perché, ma mi da errore:

Proprietà o metodo non supportati dall'oggetto: linea 355 carattere 13

Cordiali saluti.

**Comment by nicholasruggeri** [comment]
Ciao @lianix1, mi dispiace ma al momento IE8 non viene supportato/testato.
