### ISSUE TITLE
click outside don't work

### ISSUE THREAD

**Issue by Rey46** [nicholasruggeri/cookies-enabler#38]
Hello,
this is the demo inside the zip and I added a select or a textarea but the click outside don't work, why? I'm making something wrong? For which elements works correctly?

edit: Non mi ero accorto fossi italiano :) Ho preso il file di esempio dallo zip ma non funziona, dove sbaglio?

![senza-titolo-1](https://cloud.githubusercontent.com/assets/12893470/8157786/b705b56e-1357-11e5-89b0-79c5a49d4fcf.gif)

**Comment by nicholasruggeri** [comment]
Hi @Rey46, change "clickOutside: false" in "clickOutside: true".

Ciao @Rey46, nella demo è settata su false l'opzione clickOutside mettila a true :)

**Comment by Rey46** [comment]
Ho ovviamente usato la demo "demo_click_outside.html" che ha il true già attivo, non va :\

![click](https://cloud.githubusercontent.com/assets/12893470/8163261/58cb39b2-1382-11e5-947c-95fd666f8fc1.gif)

**Comment by nicholasruggeri** [comment]
Quelle demo le ho eliminate, siamo in fase di redesign del plugin e delle demo.
Scarica l'ultima versione, ho testato al volo e funziona :)

**Comment by Rey46** [comment]
Confermo che con il nuovo update funziona, ottimo plugin :+1:
