### ISSUE TITLE
banner not recognized

### ISSUE THREAD

**Issue by charango62** [nicholasruggeri/cookies-enabler#39]
Ciao Nicholas, ho provato il tuo plugin che sembra essere quello più vicino alle direttive del garante della privacy italiano.
Ho un problema di banner non trovato alla riga 225 di cookies-enabler.js:
Uncaught TypeError: Cannot read property 'style' of undefined
dismiss
(anonymous function)
window.COOKIES_ENABLER.window.COOKIES_ENABLER.later

quando si fa un'azione che dovrebbe far scomparire il banner e accettare i cookie il banner sembra non sia definito
domElmts.banner[0].style.display = 'none';

Inoltre cliccando su link presenti nella pagina ma non appartenenti a elementi generati dallo script i cookie non vengono accettati pur avendo settato clickOutside: true

ecco la mia config:
COOKIES_ENABLER.init({
    scriptClass: 'ce-script',
    iframeClass: 'ce-iframe',

```
acceptClass: 'ce-accept',
dismissClass: 'ce-dismiss',
disableClass: 'ce-disable',

bannerClass: 'ce-banner',
bannerHTML: '<p>questo sito utilizza i cookie propri e di terze parti per garantire una migliore esperienza sul sito e per la profilazione delle scelte dell’utente.<br>Utilizzando questo sito acconsenti al loro uso. <a href="cookie-policy.php">Ulteriori informazioni</a></p>',

eventScroll: true,
scrollOffset: 10,

clickOutside: true,

cookieName: 'ce-cookie',
cookieDuration: 365,

preventIframes: true,
iframesPlaceholder: true,
iframesPlaceholderHTML: '<p>Per vedere questo contenuto devi <a href="#" class="ce-accept">Accettare i cookie</a></p>',
iframesPlaceholderClass: 'ce-iframe-placeholder',
```

});

grazie

**Comment by nicholasruggeri** [comment]
Ciao @charango62, hai un link dove poter vedere l'errore?

**Comment by charango62** [comment]
puoi vederlo qui:
http://www.print66.it/branch/test.php
io uso chrome ma anche su safari c'è il problema.
ho cercato di alleggerire il più possibile la pagina evitando incompatibilità con altri script

grazie

**Comment by gsimone** [comment]
Ciao, il problema potrebbe essere con lo script che stai usando per
inserire google analytics. Prova con un javascript come

```
(function(){

   console.log('prova');

})()
```

e vedi se funziona. Credo che sia document.write a causare il problema.

On Tue, Jun 23, 2015 at 12:43 PM, charango62 notifications@github.com
wrote:

> puoi vederlo qui:
> http://www.print66.it/branch/test.php
> io uso chrome ma anche su safari c'è il problema.
> ho cercato di alleggerire il più possibile la pagina evitando
> incompatibilità con altri script
> 
> grazie
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicholasruggeri/cookies-enabler/issues/39#issuecomment-114441352
> .

## 

Gianmarco Simone

**Comment by gsimone** [comment]
Dai un occhio qui https://github.com/nicholasruggeri/cookies-enabler#problematic-scripts
