### ISSUE TITLE
Problema con eventScroll

### ISSUE THREAD

**Issue by ilPas** [nicholasruggeri/cookies-enabler#5]
Ho messo eventScroll: true tra le opzioni del plugin sul sito www.cloudprivato.com ma ho notato una cosa...il banner resta solo se si è in cima alla pagina, mentre se per caso ricarico il sito trovando in mezzo oppure arrivandoci da un'ancora scompare praticamente subito.
E' normale?

**Comment by ramspeed** [comment]
Credo proprio di si

**Comment by gsimone** [comment]
Con l'implementazione attuale è inevitabile, visto che i browser ripristinano la posizione dello scroll al ricaricamento della pagina. Ci si potrebbe lavorare intorno [ per esempio con un delay o ignorando il primo evento di scroll ], ma non so quanto sarebbe affidabile / corretto.

**Comment by effetiweb** [comment]
In the option I set eventScroll: true, is there any chance to exclude the cookie policy page from this. So only for the cookie page the evenScroll is false.
It's correct eventScroll: true along the entire website, although with this option when someone read the cookie policy and scroll to continue to reading it accept the cookie loading.

**Comment by gsimone** [comment]
You should set an id somewhere on your cookies policy page and then set the option like this:

eventScroll: (function(){ return document.getElementById('id') ? false : true })()

this will set the eventScroll as true for pages that don't have that id.
