### ISSUE TITLE
Disabilitare Video YouTube/Viemo e Google Maps

### ISSUE THREAD

**Issue by stileinverso** [nicholasruggeri/cookies-enabler#8]
Ciao, potresti aggiungere nello script l'abilitazione degli iframe convertendo la proprietà display: block; (ovviamente da css iniziale imposteremo display: none; ) ? Così siamo a posto anche con video embeddati e Google Maps. Grazie

**Comment by gsimone** [comment]
È tra le prossime feature ;)

On Tuesday, May 26, 2015, stileinverso notifications@github.com wrote:

> Ciao, potresti aggiungere nello script l'abilitazione degli iframe
> convertendo la proprietà display: block; (ovviamente da css iniziale
> imposteremo display: none; ) ? Così siamo a posto anche con video embeddati
> e Google Maps. Grazie
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nicholasruggeri/cookies-enabler/issues/8.

## 

Gianmarco Simone

**Comment by andyprog** [comment]
Ciao, l'abilitazione degli iframe avverrà sempre aggiungendo manualmente una classe ad ogni iframe? 
o è possibile disabilitare tutti gli iframe in blocco?

**Comment by nicholasruggeri** [comment]
Ciao @andyprog, per bloccare preventivamente gli iframe bisognerà dare una classe ad ogni iframe (ce-iframe o quella che preferisci settandola nelle opzioni dell'init) e cambiare "src" in "data-ce-src" in modo che non venga scaricato. Purtroppo l'iframe viene inizializato non appena la pagina viene caricata e quindi è impossibile intervenire via js dopo il load.
