### ISSUE TITLE
Disattivazione cookie dopo accettazione

### ISSUE THREAD

**Issue by andyprog** [nicholasruggeri/cookies-enabler#9]
Ciao prevedete di implementare un sistema tipo quello di fiat.it?
Ovvero la possibilità di disattivarei cookie in qualsiasi momento? (fiat permette di farlo non per singoli cookie, ma per 3 grandi gruppi in cui li ha suddivisi)

**Comment by nicholasruggeri** [comment]
Questa feature sarà nella prossima major release ;)
